#!/usr/bin/env bash
# Build-time half: install the two tools, create the uid the whole design hinges on, and bake the
# options into a config the runtime can read.
#
# No rules are applied here. The firewall belongs to the entrypoint, because a build layer is not
# where you want a default-deny network -- later features install *after* this one and would find
# the network cut from under them.
set -euo pipefail

PRESETS="${PRESETS:-}"
ALLOW="${ALLOW:-}"
DENY="${DENY:-}"
BASELINE="${BASELINE:-true}"
PROJECT_ALLOWLIST="${PROJECTALLOWLIST:-/workspaces/*/.devcontainer/egress-allow.txt}"
ALLOW_DNS="${ALLOWDNS:-true}"
DNS_SERVERS="${DNSSERVERS:-}"
PROXY_PORT="${PROXYPORT:-3128}"

SHARE_DIR=/usr/local/share/nshafer-egress-filter

# Needed only so the agent notes can be written into the right home at container start.
USERNAME="${_REMOTE_USER:-root}"
USER_HOME="${_REMOTE_USER_HOME:-}"
if [ -z "$USER_HOME" ] || [ ! -d "$USER_HOME" ]; then
    USER_HOME="$(getent passwd "$USERNAME" 2>/dev/null | cut -d: -f6 || true)"
fi
: "${USER_HOME:=/home/$USERNAME}"
PROXY_USER=egressfilter

case "$PROXY_PORT" in
    '' | *[!0-9]*)
        echo "!!! egress-filter: proxyPort must be a number. Received: $PROXY_PORT" >&2
        exit 1
        ;;
esac

# Shape-checked here as well as at container start, so a typo fails the build rather than quietly
# costing you name resolution in a container that otherwise looks fine. Addresses only: this ends
# up as an iptables -d, and a hostname would have to be resolved to be used, which is circular.
for ns in $(echo "$DNS_SERVERS" | tr ',' ' '); do
    if ! echo "$ns" | grep -qE '^([0-9]{1,3}\.){3}[0-9]{1,3}(/[0-9]{1,2})?$'; then
        echo "!!! egress-filter: dnsServers takes IPv4 addresses or CIDRs. Received: $ns" >&2
        exit 1
    fi
done

echo "==> egress-filter: baseline=$BASELINE presets=${PRESETS:-none} dns=$ALLOW_DNS" \
     "resolvers=${DNS_SERVERS:-from /etc/resolv.conf} port=$PROXY_PORT"

# Installing the feature is what turns filtering on -- there is no enabled option, because not
# wanting a default-deny network is expressed by not adding the feature.
missing=""
command -v tinyproxy >/dev/null 2>&1 || missing="$missing tinyproxy"
command -v iptables  >/dev/null 2>&1 || missing="$missing iptables"

if [ -n "$missing" ]; then
    echo "==> egress-filter: installing$missing"
    if command -v apt-get >/dev/null 2>&1; then
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -y
        # shellcheck disable=SC2086
        apt-get install -y --no-install-recommends $missing
        rm -rf /var/lib/apt/lists/*
    elif command -v apk >/dev/null 2>&1; then
        # shellcheck disable=SC2086
        apk add --no-cache $missing
    else
        echo "!!! egress-filter: no known package manager; the filter will not be able to start" >&2
    fi
fi

# The uid is the enforcement boundary. Everything the agent runs is some other uid and lands on the
# REJECT rule; only this one is allowed out, and it owns nothing else in the container. Created as a
# system user with no login shell, so it is a network identity rather than an account.
if ! id "$PROXY_USER" >/dev/null 2>&1; then
    if command -v useradd >/dev/null 2>&1; then
        useradd -r -M -s /usr/sbin/nologin "$PROXY_USER"
    else
        adduser -S -H -s /sbin/nologin "$PROXY_USER" 2>/dev/null || true
    fi
    echo "==> egress-filter: created $PROXY_USER (uid $(id -u "$PROXY_USER" 2>/dev/null || echo '?'))"
fi

install -d "$SHARE_DIR" /etc/nshafer-egress-filter
install -m 0755 egress.sh "$SHARE_DIR/egress.sh"
install -m 0755 entrypoint.sh "$SHARE_DIR/entrypoint.sh"
install -m 0755 post-attach.sh "$SHARE_DIR/post-attach.sh"
install -m 0644 baseline-allow.txt "$SHARE_DIR/baseline-allow.txt"
install -m 0644 403.html "$SHARE_DIR/403.html"
install -m 0644 BLOCKED.md "$SHARE_DIR/BLOCKED.md"
install -d "$SHARE_DIR/presets"
install -m 0644 presets/*.txt "$SHARE_DIR/presets/"

# The runtime scripts are lifecycle commands and entrypoints: static strings, handed no options.
cat > "$SHARE_DIR/config" <<EOF
# Generated by the egress-filter devcontainer feature at build time. Read by egress.sh.
PRESETS="$PRESETS"
ALLOW="$ALLOW"
DENY="$DENY"
BASELINE=$BASELINE
PROJECT_ALLOWLIST="$PROJECT_ALLOWLIST"
ALLOW_DNS=$ALLOW_DNS
DNS_SERVERS="$DNS_SERVERS"
PROXY_PORT=$PROXY_PORT
PROXY_USER=$PROXY_USER
USERNAME=$USERNAME
USER_HOME=$USER_HOME
EOF
chmod 0644 "$SHARE_DIR/config"

# One command a human types, and it only reads. There is deliberately no command for adding a host:
# anything the container's own user could run to widen the allowlist would be a way for the agent to
# widen it too, which is the whole thing this feature is trying to prevent.
cat > /usr/local/bin/egress-status <<EOF
#!/bin/sh
exec $SHARE_DIR/egress.sh status
EOF
install -m 0755 egress-denied.sh /usr/local/bin/egress-denied
chmod 0755 /usr/local/bin/egress-status

echo "==> egress-filter: build stage done"
