#!/usr/bin/env bash
# Build-time half: install the two tools, create the uid the whole design hinges on, and bake the
# options into a config the runtime can read.
#
# No rules are applied here. The firewall belongs to the entrypoint, because a build layer is not
# where you want a default-deny network -- later features install *after* this one and would find
# the network cut from under them.
set -euo pipefail

PRESETS="${PRESETS:-}"
ALLOW="${ALLOW:-}"
DENY="${DENY:-}"
BASELINE="${BASELINE:-true}"
PROJECT_ALLOWLIST="${PROJECTALLOWLIST:-/workspaces/*/.devcontainer/egress-allow.txt}"
ALLOW_DNS="${ALLOWDNS:-true}"
DNS_SERVERS="${DNSSERVERS:-}"
LOCAL_NETWORKS="${LOCALNETWORKS:-auto}"
NO_PROXY_EXTRA="${NOPROXY:-}"
UPSTREAM_PROXY="${UPSTREAMPROXY:-auto}"
PROXY_PORT="${PROXYPORT:-3128}"

SHARE_DIR=/usr/local/share/devcontainer/egress-filter

# Needed only so the agent notes can be written into the right home at container start.
USERNAME="${_REMOTE_USER:-root}"
USER_HOME="${_REMOTE_USER_HOME:-}"
if [ -z "$USER_HOME" ] || [ ! -d "$USER_HOME" ]; then
    USER_HOME="$(getent passwd "$USERNAME" 2>/dev/null | cut -d: -f6 || true)"
fi
: "${USER_HOME:=/home/$USERNAME}"
PROXY_USER=egressfilter

case "$PROXY_PORT" in
    '' | *[!0-9]*)
        echo "!!! egress-filter: proxyPort must be a number. Received: $PROXY_PORT" >&2
        exit 1
        ;;
esac

# Shape-checked here as well as at container start, so a typo fails the build rather than quietly
# costing you name resolution in a container that otherwise looks fine. Addresses only: this ends
# up as an iptables -d, and a hostname would have to be resolved to be used, which is circular.
for ns in $(echo "$DNS_SERVERS" | tr ',' ' '); do
    if ! echo "$ns" | grep -qE '^([0-9]{1,3}\.){3}[0-9]{1,3}(/[0-9]{1,2})?$'; then
        echo "!!! egress-filter: dnsServers takes IPv4 addresses or CIDRs. Received: $ns" >&2
        exit 1
    fi
done

# Same shape check as dnsServers, and for the same reason: a typo here is not a build error, it is
# a container where the database is unreachable and nothing says why. "auto" and "off" are the two
# words; everything else is a list of addresses.
case "$LOCAL_NETWORKS" in
    auto | off | false | none | '') ;;
    *)
        for net in $(echo "$LOCAL_NETWORKS" | tr ',' ' '); do
            if ! echo "$net" | grep -qE '^([0-9]{1,3}\.){3}[0-9]{1,3}(/[0-9]{1,2})?$'; then
                echo "!!! egress-filter: localNetworks takes 'auto', 'off', or IPv4 CIDRs." \
                     "Received: $net" >&2
                exit 1
            fi
        done
        ;;
esac

echo "==> egress-filter: baseline=$BASELINE presets=${PRESETS:-none} dns=$ALLOW_DNS" \
     "resolvers=${DNS_SERVERS:-from /etc/resolv.conf} local=$LOCAL_NETWORKS port=$PROXY_PORT"

# Installing the feature is what turns filtering on -- there is no enabled option, because not
# wanting a default-deny network is expressed by not adding the feature.
missing=""
command -v tinyproxy >/dev/null 2>&1 || missing="$missing tinyproxy"
command -v iptables  >/dev/null 2>&1 || missing="$missing iptables"

if [ -n "$missing" ]; then
    echo "==> egress-filter: installing $missing"
    if command -v apt-get >/dev/null 2>&1; then
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -y
        # shellcheck disable=SC2086
        apt-get install -y --no-install-recommends $missing
        rm -rf /var/lib/apt/lists/*
    elif command -v apk >/dev/null 2>&1; then
        # shellcheck disable=SC2086
        apk add --no-cache $missing
    else
        echo "!!! egress-filter: no known package manager; the filter will not be able to start" >&2
    fi
fi

# The uid is the enforcement boundary. Everything the agent runs is some other uid and lands on the
# REJECT rule; only this one is allowed out, and it owns nothing else in the container. Created as a
# system user with no login shell, so it is a network identity rather than an account.
if ! id "$PROXY_USER" >/dev/null 2>&1; then
    if command -v useradd >/dev/null 2>&1; then
        useradd -r -M -s /usr/sbin/nologin "$PROXY_USER"
    else
        adduser -S -H -s /sbin/nologin "$PROXY_USER" 2>/dev/null || true
    fi
    echo "==> egress-filter: created $PROXY_USER (uid $(id -u "$PROXY_USER" 2>/dev/null || echo '?'))"
fi

install -d "$SHARE_DIR" /etc/devcontainer/egress-filter
install -m 0755 egress.sh "$SHARE_DIR/egress.sh"
install -m 0755 entrypoint.sh "$SHARE_DIR/entrypoint.sh"
install -m 0755 post-attach.sh "$SHARE_DIR/post-attach.sh"
install -m 0644 baseline-allow.txt "$SHARE_DIR/baseline-allow.txt"
install -m 0644 403.html "$SHARE_DIR/403.html"
install -m 0644 BLOCKED.md "$SHARE_DIR/BLOCKED.md"
install -d "$SHARE_DIR/presets"
install -m 0644 presets/*.txt "$SHARE_DIR/presets/"

# The runtime scripts are lifecycle commands and entrypoints: static strings, handed no options.
cat > "$SHARE_DIR/config" <<EOF
# Generated by the egress-filter devcontainer feature at build time. Read by egress.sh.
PRESETS="$PRESETS"
ALLOW="$ALLOW"
DENY="$DENY"
BASELINE=$BASELINE
PROJECT_ALLOWLIST="$PROJECT_ALLOWLIST"
ALLOW_DNS=$ALLOW_DNS
DNS_SERVERS="$DNS_SERVERS"
LOCAL_NETWORKS="$LOCAL_NETWORKS"
NO_PROXY_EXTRA="$NO_PROXY_EXTRA"
UPSTREAM_PROXY="$UPSTREAM_PROXY"
PROXY_PORT=$PROXY_PORT
PROXY_USER=$PROXY_USER
USERNAME=$USERNAME
USER_HOME=$USER_HOME
EOF
chmod 0644 "$SHARE_DIR/config"

# One command a human types, and it only reads. There is deliberately no command for adding a host:
# anything the container's own user could run to widen the allowlist would be a way for the agent to
# widen it too, which is the whole thing this feature is trying to prevent.
cat > /usr/local/bin/egress-status <<EOF
#!/bin/sh
exec $SHARE_DIR/egress.sh status
EOF
install -m 0755 egress-denied.sh /usr/local/bin/egress-denied
chmod 0755 /usr/local/bin/egress-status

# The one thing that has to happen at build time rather than at container start.
#
# dockerd reads /etc/docker/daemon.json once, when it starts, and entrypoints run in install order.
# So when the docker-in-docker feature installs *before* this one, its entrypoint runs first, dockerd
# is already up by the time egress.sh gets a turn, and the daemon.json egress.sh writes is too late
# to be read. The daemon then pulls without the proxy and fails with registry timeouts.
#
# In exactly that ordering, dockerd is installed by the time this script runs. So the file goes into
# the image here, before any daemon can start, and the ordering stops mattering. egress.sh rewrites
# it at container start with the real local subnets, which is what a daemon starting later reads.
#
# localNetworks is forced off for this call: local_networks would otherwise read the *build*
# container's routing table, and those subnets are not the ones the container will run on.
if command -v dockerd >/dev/null 2>&1 || command -v docker >/dev/null 2>&1; then
    if EGRESS_LOCAL_NETWORKS=off "$SHARE_DIR/egress.sh" docker-conf; then
        echo "==> egress-filter: wrote /etc/docker/daemon.json for the inner daemon"
    else
        echo "!!! egress-filter: could not write /etc/docker/daemon.json. If dockerd starts before" >&2
        echo "!!!   this feature's entrypoint, its pulls will fail as registry timeouts." >&2
    fi
fi

# The second thing that has to happen at build time, and for the same shape of reason.
#
# VS Code execs its server into the container as soon as the container is running, which can be
# seconds before this feature's entrypoint gets a turn. The server runs its environment probe then
# -- a login shell, by default -- and whatever that probe returns is what the extension host and
# every process it starts carry for the life of the window. A probe that runs before the entrypoint
# writes /etc/profile.d finds no proxy, and nothing later corrects it.
#
# So the file goes into the image here, and the ordering stops mattering. egress.sh rewrites it at
# container start with the real local subnets, and only when the content changes.
#
# The profile.d file alone. /etc/environment is read by pam_env for `su`, so writing it here would
# point a later feature that installs anything as the remote user at a proxy that does not exist
# until the container starts.
#
# localNetworks is forced off for the same reason as above: the build container's routing table is
# not the one this container will run on.
if EGRESS_LOCAL_NETWORKS=off "$SHARE_DIR/egress.sh" env profile; then
    echo "==> egress-filter: wrote /etc/profile.d/00-devcontainer-egress-filter.sh"
else
    echo "!!! egress-filter: could not write the profile.d file. A VS Code server that starts" >&2
    echo "!!!   before this feature's entrypoint will carry no proxy." >&2
fi

echo "==> egress-filter: build stage done"
