# Test runner for the features in src/.
#
# The whole point is that `devcontainer features test` needs three things right before it does
# anything useful -- the correct CLI, a base image the feature can actually be exercised on, and
# the host paths its mounts expect -- and none of them are the default. This puts those in one
# place so a test run is `make sandbox` rather than a remembered incantation.
#
# Usage:
#   make                          # help
#   make test                     # every feature, autogenerated tests and scenarios
#   make sandbox                  # one feature
#   make sandbox QUICK=1          # ... skipping its scenarios, for an edit-run loop
#   make sandbox FILTER=wayland   # ... narrowing the scenarios to ones named like this
#   make sandbox FILTER=wayland SCENARIOS_ONLY=1   # ... and nothing else at all
#   make sandbox ARGS=--log-level=debug
#   make -k test                  # keep going after a failing feature, the way CI does

FEATURES := $(notdir $(wildcard src/*))

# npx, not the `devcontainer` on PATH. A machine with VS Code installed has a wrapper of that name
# in ~/bin which appends --workspace-folder to whatever it is given, and `features test` rejects
# that argument outright ("Unknown arguments: workspace-folder"). Override with CLI=... if your
# devcontainer binary is the real one.
CLI ?= npx --yes @devcontainers/cli@latest

# The harness defaults to ubuntu:focal running as root, which exercises none of the interesting
# paths: every feature here keys off a non-root remote user's home directory.
IMAGE_DEFAULT := node
USER_DEFAULT  := node

# Per-feature overrides, and there is one. sandbox's tests have to become root to check what the
# *remote user* can no longer reach, and the plain node image ships no sudo. Keep this in step with
# the matrix in .github/workflows/test.yaml.
IMAGE_sandbox := mcr.microsoft.com/devcontainers/javascript-node:20
IMAGE_egress-filter := mcr.microsoft.com/devcontainers/javascript-node:20

# IMAGE=/USER= on the command line beat the per-feature value, which beats the default.
image_for = $(if $(IMAGE),$(IMAGE),$(if $(IMAGE_$(1)),$(IMAGE_$(1)),$(IMAGE_DEFAULT)))
user_for  = $(if $(USER_OVERRIDE),$(USER_OVERRIDE),$(if $(USER_$(1)),$(USER_$(1)),$(USER_DEFAULT)))

# QUICK and FILTER are shorthands for the two flags worth typing often. They are mutually
# exclusive in the CLI itself, so say so here rather than letting it fail three minutes in.
TEST_ARGS := $(ARGS)
ifdef QUICK
  ifdef FILTER
    $(error QUICK and FILTER cannot be combined -- --skip-scenarios and --filter are exclusive)
  endif
  TEST_ARGS += --skip-scenarios
endif
ifdef FILTER
  TEST_ARGS += --filter $(FILTER)
endif
ifdef SCENARIOS_ONLY
  TEST_ARGS += --skip-autogenerated
endif

.DEFAULT_GOAL := help

.PHONY: help test quick scenarios lint shellcheck setup clean list

help:
	@echo "Features:  $(FEATURES)"
	@echo ""
	@echo "  make test                  every feature (use -k to keep going after a failure)"
	@echo "  make <feature>             one feature, e.g. make sandbox"
	@echo "  make quick                 every feature, scenarios skipped"
	@echo "  make scenarios             scenarios only, autogenerated tests skipped"
	@echo "  make lint                  shellcheck + shell/python syntax + JSON validity, no containers"
	@echo "  make shellcheck            shellcheck alone"
	@echo "  make setup                 create the host paths the mounts need"
	@echo "  make clean                 remove leftover test containers"
	@echo "  make list                  show the image each feature is tested on"
	@echo ""
	@echo "Variables:  QUICK=1  FILTER=<scenario>  SCENARIOS_ONLY=1  ARGS=<extra flags>"
	@echo "            FILTER narrows the scenarios only; add SCENARIOS_ONLY=1 to skip test.sh too"
	@echo "            IMAGE=<image>  USER_OVERRIDE=<user>  CLI=<devcontainer cli>"

list:
	@printf '%-18s %-14s %s\n' FEATURE USER IMAGE
	@$(foreach f,$(FEATURES),printf '%-18s %-14s %s\n' '$(f)' '$(call user_for,$(f))' '$(call image_for,$(f))';)

# One explicit pair of rules per feature, generated rather than written out, so adding a feature
# under src/ is all it takes. Explicit and not a `test-%` pattern rule on purpose: GNU make skips
# implicit-rule search for anything declared .PHONY, so a pattern rule plus the .PHONY these need
# (there is a real ./test directory, and a feature could share a name with a target) silently
# resolves to "Nothing to be done".
#
# `make sandbox` and `make test-sandbox` both work; the bare name is the one worth typing.
define FEATURE_RULE
.PHONY: $(1) test-$(1)
$(1): test-$(1)
test-$(1): setup
	@echo "==> $(1) on $$(call image_for,$(1)) as $$(call user_for,$(1))"
	$$(CLI) features test -f $(1) -i $$(call image_for,$(1)) -u $$(call user_for,$(1)) $$(TEST_ARGS) .
endef
$(foreach f,$(FEATURES),$(eval $(call FEATURE_RULE,$(f))))

test: $(addprefix test-,$(FEATURES))

quick:
	@$(MAKE) test QUICK=1

scenarios:
	@$(MAKE) test SCENARIOS_ONLY=1

# The mounts are applied by the harness, and a bind mount whose source does not exist stops the
# container from starting outright -- Docker does not create it, that is -v behaviour rather than
# --mount. Only git-config and egress-filter mount a host path, and both mount a directory, so the
# directory is what has to exist. The two files are for the tests, which read what the mount
# carries. Deliberately does not touch ~/.gitconfig: if that file exists, git ignores ~/.config/git
# entirely, so creating an empty one would switch off the whole configuration of an XDG setup.
setup:
	@mkdir -p $(HOME)/.config/git $(HOME)/.config/egress-filter
	@[ -e $(HOME)/.config/git/config ] || : > $(HOME)/.config/git/config
	@[ -e $(HOME)/.config/egress-filter/allowlist.txt ] \
	    || printf '# Hosts every dev container may reach. .example.com covers subdomains.\n' \
	       > $(HOME)/.config/egress-filter/allowlist.txt

# The test scripts are linted with three checks off, and all three are structural rather than
# sloppiness -- suppressing them per-line would mean a directive on nearly every check in the suite:
#
#   SC2016  the `check "..." bash -c '...$VAR...'` idiom. Single quotes are the whole point: the
#           expansion has to happen in the inner shell, not when the test script is read.
#   SC1091  `source dev-container-features-test-lib`, which only exists inside the test container.
#   SC2088  a literal ~ inside a check's human-readable description string, which is prose and not
#           a path. Both hits are in descriptions.
#
# src/ gets no exclusions at all -- what ships is held to the stricter standard, and the handful of
# deliberate patterns in there carry their own inline directives with a reason next to each.
SHELLCHECK ?= shellcheck
TEST_SUPPRESSIONS := SC2016,SC1091,SC2088

# Missing shellcheck is a skip locally -- it should not stop someone running the tests -- but a
# hard failure where STRICT=1 is set, so the CI check cannot quietly decay into a no-op if the
# runner image ever drops the tool.
# One shell for the whole recipe, not the usual line-per-shell: the "skip" branch has to be able
# to exit before the checks below it, and an `exit 0` on its own line would only end that line.
shellcheck:
	@if ! command -v $(SHELLCHECK) >/dev/null 2>&1; then \
	    if [ -n "$(STRICT)" ]; then \
	        echo "!!! shellcheck is not installed and STRICT is set"; exit 1; \
	    fi; \
	    echo "shellcheck not installed -- skipping (apt/brew install shellcheck)"; exit 0; \
	fi; \
	set -e; \
	echo "$(SHELLCHECK) src/*/*.sh"; \
	$(SHELLCHECK) src/*/*.sh; \
	echo "$(SHELLCHECK) -e $(TEST_SUPPRESSIONS) test/*/*.sh"; \
	$(SHELLCHECK) -e $(TEST_SUPPRESSIONS) test/*/*.sh; \
	echo "shellcheck ok"

# No containers, no network, no minutes. Catches the class of mistake that otherwise shows up three
# minutes into an image build.
lint: shellcheck
	@fail=0; \
	for f in src/*/*.sh test/*/*.sh; do \
	    bash -n "$$f" || { echo "!!! syntax: $$f"; fail=1; }; \
	done; \
	python3 -c "import ast,sys; ast.parse(open(sys.argv[1]).read())" bin/devc \
	    || { echo "!!! syntax: bin/devc"; fail=1; }; \
	for f in src/*/devcontainer-feature.json test/*/scenarios.json; do \
	    python3 -c "import json,sys; json.load(open(sys.argv[1]))" "$$f" \
	        || { echo "!!! json: $$f"; fail=1; }; \
	done; \
	for d in $(FEATURES); do \
	    id=$$(python3 -c "import json;print(json.load(open('src/$$d/devcontainer-feature.json'))['id'])"); \
	    [ "$$id" = "$$d" ] || { echo "!!! src/$$d declares id '$$id'"; fail=1; }; \
	done; \
	[ $$fail -eq 0 ] && echo "lint ok"; exit $$fail

# Scoped to the label the harness stamps on its own containers, so this cannot reach anything else
# running on the machine.
clean:
	@ids=$$(docker ps -aq --filter label=devcontainer.is_test_run=true); \
	if [ -n "$$ids" ]; then docker rm -f $$ids; else echo "no test containers"; fi
