#!/usr/bin/env bash
# Shared by test.sh and the scenarios. Sourced, never run directly -- the harness only executes
# test.sh and the scripts named in scenarios.json, so a leading underscore is convention rather
# than protection.
#
# Nothing here needs root. That is the point: with dropSudo on by default the autogenerated test
# runs as a user who cannot become root, which is exactly the vantage point most of these checks
# want anyway -- they are claims about what the *remote user* can no longer do.

# Every sudo in this suite is `sudo -n`, and it matters more than it looks. With dropSudo on there
# is no grant, so a bare `sudo` does not fail -- it falls back to prompting on the terminal, and the
# run stops dead waiting for a password nobody is going to type. Interactively that is an annoyance;
# in CI it is a job that hangs until the step times out rather than one that reports a failure.
# -n makes sudo exit non-zero instead of asking, which is what a test wants either way. Passwordless
# grants are unaffected, so the scenarios that keep sudo work exactly the same.
#
# Belt and braces for anything that forgets: with no askpass helper configured and stdin closed,
# sudo has nowhere to read a password from even if -n is missed.
export SUDO_ASKPASS=/bin/false

# A directory the remote user can write, since /usr/local/bin needs root once sudo is gone.
SBX_BIN=/tmp/sbx-bin
mkdir -p "$SBX_BIN"
export PATH="$SBX_BIN:$PATH"

# perl, because it is the one interpreter present in every image this suite runs on (the Debian
# base has no python3 and no node). A unix socket outlives the process that bound it, so
# bind-and-exit leaves behind exactly the artifact VS Code leaves behind.
cat > "$SBX_BIN/sock-bind" <<'PERL'
#!/usr/bin/perl
use strict; use Socket;
socket(my $s, PF_UNIX, SOCK_STREAM, 0) or die "socket: $!\n";
bind($s, sockaddr_un($ARGV[0])) or die "bind refused: $!\n";
listen($s, 1);
print "bound $ARGV[0]\n";
PERL

cat > "$SBX_BIN/sock-connect" <<'PERL'
#!/usr/bin/perl
use strict; use Socket;
socket(my $s, PF_UNIX, SOCK_STREAM, 0) or die "socket: $!\n";
connect($s, sockaddr_un($ARGV[0])) or die "connect refused: $!\n";
print "connected $ARGV[0]\n";
PERL

# "How many sweepers are running" is not the same question as "how many processes match", and
# pgrep only answers the second. The daemon runs `find ... | while read` on every pass, and bash
# forks a subshell for the right-hand side of a pipeline; that subshell inherits the parent's
# command line verbatim. Measured over 400 samples against a busy daemon, a raw count was wrong 37
# times -- an intermittent failure that took a while to pin down. Filtering by parent does not help
# either (also 37/400): a subshell whose parent has exited is reparented to init.
#
# Session leadership does, and was wrong 0 times out of 400. The entrypoint starts the daemon under
# setsid, so it leads its session -- pid == sid -- while its subshells inherit that session without
# leading it.
cat > "$SBX_BIN/count-sweepers" <<'SH'
#!/bin/sh
command -v setsid >/dev/null 2>&1 || {
    echo "count-sweepers: no setsid, so sweepers are not session leaders and cannot be counted" >&2
    exit 1
}
pids=$(pgrep -f 'sandbox\.sh daemon' 2>/dev/null || true)
[ -n "$pids" ] || { echo 0; exit 0; }
ps -o pid=,sess= -p "$(echo $pids | tr ' ' ',')" 2>/dev/null | awk '$1 == $2' | wc -l
SH

# Waits for the sweeper to take a path, rather than driving a sweep directly. Without sudo that is
# the only way to observe sealing -- and it is the truer test, because it exercises the path that
# actually runs in a real container instead of a hand-invoked sweep.
#
# A script rather than a shell function: `check` runs each body in its own `bash -c`, which does not
# inherit functions from here.
cat > "$SBX_BIN/wait-sealed" <<'SH'
#!/bin/sh
path="$1"; limit="${2:-20}"; i=0
while [ "$i" -lt "$limit" ]; do
    [ "$(stat -c %a "$path" 2>/dev/null)" = 0 ] && exit 0
    i=$((i + 1))
    sleep 1
done
echo "wait-sealed: $path was never sealed after ${limit}s" >&2
exit 1
SH

chmod 0755 "$SBX_BIN"/*
