#!/usr/bin/env bash
# Defaults, as the autogenerated test.sh runs them, but as root. Two properties cannot be proven
# from a non-root process at all: what the iptables chain actually contains, and that a rebuild
# picks up the project allowlist the way a container restart would.
#
# Root and not sudo, because sudo is setuid, and a container that carries no_new_privs refuses to
# run it -- which is every container a dockerd inside a sandboxed dev container starts. Root is not
# exempt from the filter either (only the proxy uid is), so the reachability checks below still
# measure the filter and not a hole in it.
set -e
source dev-container-features-test-lib

fetch()  { timeout 15 curl -s -o /dev/null -w "%{http_code}" -x "http://127.0.0.1:3128" "https://$1" 2>/dev/null || echo 000; }
direct() { timeout 10 curl -s -o /dev/null -w "%{http_code}" --noproxy "*" "https://$1" 2>/dev/null || echo 000; }
export -f fetch direct

check "a host on no list is blocked to begin with" bash -c '
    code=$(fetch example.com); echo "  example.com=$code"
    [ "$code" != 200 ] || { echo "reachable before being allowed; the filter is not filtering"; exit 1; }'

# The project list is not re-read while the container runs -- test.sh proves that, since it is the
# security property and belongs with the unprivileged suite. This is the other half: the list IS
# honoured on the next start, which is what makes it useful at all. A rebuild stands in for the
# restart, because it reads the same three sources in the same order.
check "the project list is picked up by a privileged rebuild, as a restart would" bash -c '
    d=$(ls -d /workspaces/*/ | head -1); mkdir -p "$d.devcontainer"
    echo "example.com" >> "$d.devcontainer/egress-allow.txt"
    echo "  wrote example.com to $d.devcontainer/egress-allow.txt"
    /usr/local/share/devcontainer/egress-filter/egress.sh reload >/dev/null 2>&1
    for _ in $(seq 1 10); do
        code=$(fetch example.com); [ "$code" = 200 ] && break
        sleep 1
    done
    echo "  example.com=$code"
    [ "$code" = 200 ] || { echo "a restart would not have picked it up either"; exit 1; }'

check "the project list is reported as a source once the rebuild has read it" bash -c '
    egress-status | tee /dev/stderr | grep -q "project:  /workspaces"'

check "allowing one host did not open the rest" bash -c '
    code=$(fetch neverallowed.example.net); echo "  neverallowed.example.net=$code"
    [ "$code" != 200 ]'

# The point of the firewall rather than just the env var: ignoring the proxy does not help, even for
# a host that IS allowed, and even for root.
check "ignoring HTTP_PROXY does not get you out" bash -c '
    code=$(direct example.com); echo "  direct to the allowed host=$code"
    [ "$code" != 200 ] || { echo "egress bypassed the proxy entirely"; exit 1; }'

# Port 53 is the one hole a default-deny egress filter has to leave open, and open to *any*
# destination it is not a hole but a transport: iodine and dnscat need nothing more than a route to
# a nameserver the other end controls. So the accepts name a destination, and the destinations are
# the resolvers this container was actually given.
check "port 53 is pinned to the resolvers this container was given" bash -c '
    dns=$(iptables -S DEVCONTAINER_EGRESS | grep -- "--dport 53" || true)
    echo "$dns" | sed "s/^/  /"
    [ -n "$dns" ] || { echo "no DNS rules at all"; exit 1; }
    open=$(echo "$dns" | grep -- "-j ACCEPT" | grep -cv -- " -d " || true)
    [ "$open" = 0 ] || { echo "$open DNS accepts with no destination -- 53 is open to the world"; exit 1; }
    for ns in $(sed -n "s/^nameserver  *//p" /etc/resolv.conf); do
        case "$ns" in *:*) continue ;; esac
        echo "$dns" | grep -q -- " -d $ns" || { echo "resolver $ns was not pinned"; exit 1; }
    done
    echo "  every accept on 53 carries a destination"'

# auto is the default, and it has to find the subnets docker actually attached this container to --
# a compose database on 5432 is a peer on one of them, and a default-deny chain rejects it exactly
# like the internet.
check "auto opened the subnets this container is attached to" bash -c '
    rules=$(iptables -S DEVCONTAINER_EGRESS)
    nets=$(ip -4 route show scope link | awk "\$1 ~ /\\// { print \$1 }")
    [ -n "$nets" ] || { echo "no on-link subnets to check"; exit 1; }
    for net in $nets; do
        echo "$rules" | grep -q -- "-d $net -j ACCEPT" \
            || { echo "$net is attached but was not opened"; echo "$rules" | sed "s/^/  /"; exit 1; }
        echo "  $net is reachable directly"
    done'

check "egress-status reports the same subnets" bash -c '
    out=$(egress-status | tee /dev/stderr)
    for net in $(ip -4 route show scope link | awk "\$1 ~ /\\// { print \$1 }"); do
        echo "$out" | grep -q "$net" || { echo "$net is open but unreported"; exit 1; }
    done'

# The local accepts match on destination only, so they cannot become a route to the internet.
check "every local accept carries a destination" bash -c '
    open=$(iptables -S DEVCONTAINER_EGRESS | grep -- "-j ACCEPT" \
        | grep -v -- " -d " | grep -v -- "--uid-owner" | grep -v -- "-o lo" | grep -v -- "--state" || true)
    [ -z "$open" ] || { echo "an accept with no destination: $open"; exit 1; }
    echo "  no unqualified accept in the chain"'

# The rule the whole design rests on: one uid gets out, everything else lands on the REJECT.
check "the chain lets exactly one uid out" bash -c '
    rules=$(iptables -S DEVCONTAINER_EGRESS)
    echo "$rules" | sed "s/^/  /"
    uid=$(id -u egressfilter)
    echo "$rules" | grep -q -- "--uid-owner $uid -j ACCEPT" || { echo "the proxy uid is not exempt"; exit 1; }
    [ "$(echo "$rules" | grep -c -- "--uid-owner")" = 1 ] || { echo "another uid is exempt too"; exit 1; }
    echo "$rules" | tail -1 | grep -q -- "-j REJECT" || { echo "the chain does not end in REJECT"; exit 1; }'

# The failure path, which is the one that rots unnoticed: a kernel with no xt_owner, which is what a
# rootless runtime on an unprepared host gives you. Proven with a stub `iptables` first on PATH, so
# the real chain is never touched -- every call the script makes, including its own cleanup, lands
# on the stub. The state file is the one thing that really is rewritten, so it is put back after.
#
# What must hold: the chain comes down rather than being left without its owner rule (which would
# block the proxy too) or without its REJECT (which would filter nothing while reporting that it
# does), and the reason reaches the unprivileged reader.
check "a refused match brings the chain down instead of half-applying it" bash -c '
    stub=$(mktemp -d)
    cat > "$stub/iptables" <<"STUB"
#!/bin/sh
case "$*" in *--uid-owner*) exit 1 ;; esac
exit 0
STUB
    chmod +x "$stub/iptables"
    out=$(PATH="$stub:$PATH" /usr/local/share/devcontainer/egress-filter/egress.sh firewall 2>&1)
    rc=$?
    echo "$out" | sed "s/^/  /"
    # Put the real state file back before any assertion can leave the container misreported.
    /usr/local/share/devcontainer/egress-filter/egress.sh firewall >/dev/null 2>&1
    [ "$rc" != 0 ] || { echo "a missing xt_owner was reported as success"; exit 1; }
    echo "$out" | grep -q "xt_owner" || { echo "the failure did not name the module"; exit 1; }
    echo "$out" | grep -q "firewall removed" || { echo "the chain was left half-applied"; exit 1; }
    echo "$out" | grep -qi "rootless" || { echo "the hint does not mention a rootless runtime"; exit 1; }'

check "the firewall is back up, and reported, after that test" bash -c '
    iptables -C OUTPUT -j DEVCONTAINER_EGRESS || { echo "the chain was not restored"; exit 1; }
    egress-status | tee /dev/stderr | grep -q "default deny"'

reportResults
