#!/usr/bin/env bash
# Defaults, as the autogenerated test.sh runs them, but as root. Two properties cannot be proven
# from a non-root process at all: what the iptables chain actually contains, and that a rebuild
# picks up the project allowlist the way a container restart would.
#
# Root and not sudo, because sudo is setuid, and a container that carries no_new_privs refuses to
# run it -- which is every container a dockerd inside a sandboxed dev container starts. Root is not
# exempt from the filter either (only the proxy uid is), so the reachability checks below still
# measure the filter and not a hole in it.
set -e
source dev-container-features-test-lib

fetch()  { timeout 15 curl -s -o /dev/null -w "%{http_code}" -x "http://127.0.0.1:3128" "https://$1" 2>/dev/null || echo 000; }
direct() { timeout 10 curl -s -o /dev/null -w "%{http_code}" --noproxy "*" "https://$1" 2>/dev/null || echo 000; }
export -f fetch direct

check "a host on no list is blocked to begin with" bash -c '
    code=$(fetch example.com); echo "  example.com=$code"
    [ "$code" != 200 ] || { echo "reachable before being allowed; the filter is not filtering"; exit 1; }'

# The project list is not re-read while the container runs -- test.sh proves that, since it is the
# security property and belongs with the unprivileged suite. This is the other half: the list IS
# honoured on the next start, which is what makes it useful at all. A rebuild stands in for the
# restart, because it reads the same three sources in the same order.
check "the project list is picked up by a privileged rebuild, as a restart would" bash -c '
    d=$(ls -d /workspaces/*/ | head -1); mkdir -p "$d.devcontainer"
    echo "example.com" >> "$d.devcontainer/egress-allow.txt"
    echo "  wrote example.com to $d.devcontainer/egress-allow.txt"
    /usr/local/share/devcontainer/egress-filter/egress.sh reload >/dev/null 2>&1
    for _ in $(seq 1 10); do
        code=$(fetch example.com); [ "$code" = 200 ] && break
        sleep 1
    done
    echo "  example.com=$code"
    [ "$code" = 200 ] || { echo "a restart would not have picked it up either"; exit 1; }'

check "the project list is reported as a source once the rebuild has read it" bash -c '
    egress-status | tee /dev/stderr | grep -q "project:  /workspaces"'

check "allowing one host did not open the rest" bash -c '
    code=$(fetch neverallowed.example.net); echo "  neverallowed.example.net=$code"
    [ "$code" != 200 ]'

# The point of the firewall rather than just the env var: ignoring the proxy does not help, even for
# a host that IS allowed, and even for root.
check "ignoring HTTP_PROXY does not get you out" bash -c '
    code=$(direct example.com); echo "  direct to the allowed host=$code"
    [ "$code" != 200 ] || { echo "egress bypassed the proxy entirely"; exit 1; }'

# Port 53 is the one hole a default-deny egress filter has to leave open, and open to *any*
# destination it is not a hole but a transport: iodine and dnscat need nothing more than a route to
# a nameserver the other end controls. So the accepts name a destination, and the destinations are
# the resolvers this container was actually given.
check "port 53 is pinned to the resolvers this container was given" bash -c '
    dns=$(iptables -S DEVCONTAINER_EGRESS | grep -- "--dport 53" || true)
    echo "$dns" | sed "s/^/  /"
    [ -n "$dns" ] || { echo "no DNS rules at all"; exit 1; }
    open=$(echo "$dns" | grep -- "-j ACCEPT" | grep -cv -- " -d " || true)
    [ "$open" = 0 ] || { echo "$open DNS accepts with no destination -- 53 is open to the world"; exit 1; }
    for ns in $(sed -n "s/^nameserver  *//p" /etc/resolv.conf); do
        case "$ns" in *:*) continue ;; esac
        echo "$dns" | grep -q -- " -d $ns" || { echo "resolver $ns was not pinned"; exit 1; }
    done
    echo "  every accept on 53 carries a destination"'

# The rule the whole design rests on: one uid gets out, everything else lands on the REJECT.
check "the chain lets exactly one uid out" bash -c '
    rules=$(iptables -S DEVCONTAINER_EGRESS)
    echo "$rules" | sed "s/^/  /"
    uid=$(id -u egressfilter)
    echo "$rules" | grep -q -- "--uid-owner $uid -j ACCEPT" || { echo "the proxy uid is not exempt"; exit 1; }
    [ "$(echo "$rules" | grep -c -- "--uid-owner")" = 1 ] || { echo "another uid is exempt too"; exit 1; }
    echo "$rules" | tail -1 | grep -q -- "-j REJECT" || { echo "the chain does not end in REJECT"; exit 1; }'

reportResults
