#!/usr/bin/env bash
# Defaults, which means the filter is on -- installing the feature is what turns it on, so the
# autogenerated test exercises the real configuration rather than a special one.
#
# The checks that matter are the two ends of it: an allowed host is reachable, and a host that is
# on no list is not reachable *by any route*, including one that ignores HTTP_PROXY.
#
# Runs as the remote user, deliberately: this is the suite that proves what the person -- and the
# agent -- can see and do without root. Anything that needs root is in the privileged scenario.
set -e
source dev-container-features-test-lib

fetch()  { timeout 15 curl -s -o /dev/null -w "%{http_code}" -x "http://127.0.0.1:3128" "https://$1" 2>/dev/null || echo 000; }
direct() { timeout 10 curl -s -o /dev/null -w "%{http_code}" --noproxy "*" "https://$1" 2>/dev/null || echo 000; }
export -f fetch direct

check "the tools and scripts landed" bash -c '
    command -v squid     >/dev/null || { echo "no squid"; exit 1; }
    command -v iptables  >/dev/null || { echo "no iptables"; exit 1; }
    command -v egress-status >/dev/null
    # No command for widening the list from inside -- see the README.
    ! command -v egress-allow >/dev/null || { echo "egress-allow should not exist"; exit 1; }
    id egressfilter >/dev/null || { echo "no proxy uid"; exit 1; }
    test -r /usr/local/share/devcontainer/egress-filter/config'

check "the filter came up at container start" bash -c '
    egress-status | tee /dev/stderr
    egress-status | grep -q "listening on 127.0.0.1:3128"
    egress-status | grep -q "default deny"'

check "the baseline is merged, so VS Code can still reach the marketplace" bash -c '
    egress-status | grep -q "baseline:"
    grep -q "visualstudio" /etc/devcontainer/egress-filter/allow.regex'

# The global list is a file on the host, on a mount the user declares. This suite declares none, so
# the check below is what a container without that mount reports.
# allow.regex is what the proxy reads and is unreadable at a glance: anchored, escaped, sorted, with
# no trace of where any line came from. The concatenated file answers "why is this host allowed" and
# "did my edit land", which is the question anyone actually has.
check "the concatenated allowlist is written, with a header per source" bash -c '
    f=/etc/devcontainer/egress-filter/allowlist.txt
    test -r "$f" || { echo "not written"; exit 1; }
    grep -q "^# baseline: " "$f" || { echo "no baseline header"; sed -n 1,20p "$f"; exit 1; }
    # No global header here: this suite declares no mount, so the global list is not a source. The
    # mounted-global scenario checks that header.
    ! grep -q "^# global: " "$f" || { echo "a global header with no mount"; exit 1; }
    grep -q "rewritten on every reload" "$f" || { echo "no do-not-edit warning"; exit 1; }'

check "it carries the source comments through, not just the hosts" bash -c '
    f=/etc/devcontainer/egress-filter/allowlist.txt
    # The baseline explains itself; that explanation is the useful part when reading this file.
    grep -q "cannot reach the marketplace" "$f" || { echo "source comments were stripped"; exit 1; }
    grep -q "marketplace.visualstudio.com" "$f" || { echo "baseline hosts missing"; exit 1; }'

check "status points at it, so it can be found" bash -c '
    egress-status | tee /dev/stderr         | grep -qE "allowlist +[0-9]+ patterns \(/etc/devcontainer/egress-filter/allowlist.txt\)"'

check "it is readable without root" bash -c '
    head -1 /etc/devcontainer/egress-filter/allowlist.txt >/dev/null || { echo "cannot read as $(whoami)"; exit 1; }'

# /etc/environment and /etc/profile.d reach a login shell and the VS Code environment probe, and
# VS Code applies the probe to the extension host. What neither reaches is a bare `docker exec`
# from outside VS Code, and only the project's devcontainer.json can close that gap. So status
# reports which state this container is in, in one line, and points at the README for the rest --
# from lines 6 and 7 of the state file, because this runs unprivileged.
#
# Either state is correct here. This suite declares no containerEnv, so a plain host reports "not
# set". On a machine where the suite itself runs inside a filtered container the line names the
# outer proxy instead, because the outer egress-filter writes a proxies block into the docker client
# config and docker puts it on PID 1 of every container it starts. The container-env scenario pins
# the positive case.
check "status reports the container environment in one line and no more" bash -c '
    out=$(egress-status | tee /dev/stderr)
    echo "$out" | grep -qE "container env +[A-Za-z0-9]" || { echo "no container env line"; exit 1; }
    echo "$out" | grep -q "^!!!" && { echo "a warning block, which was retired"; exit 1; }
    if echo "$out" | grep -qE "container env +set -- "; then
        echo "  the environment names this proxy"; exit 0
    fi
    echo "$out" | grep -E "container env +" | grep -q "see README" ||
        { echo "the line does not point at the README"; exit 1; }
    echo "  one line, and it points at the README"'

# A client that reads HTTP_PROXY sends a request for a peer to the proxy. The firewall lets the peer
# through directly, and that used to be the only route: the proxy denied the address for not being
# a hostname on the list, which is what NO_PROXY had to name every subnet for. Now the proxy holds a
# pattern for every local subnet, so the request reaches the peer either way. Proven against this
# container's own address, which is on the subnet, with a server that answers on it.
check "the proxy forwards to a peer on the local subnet by address" bash -c '
    me=$(ip -4 -o addr show scope global | awk "{ print \$4 }" | cut -d/ -f1 | head -1)
    [ -n "$me" ] || { echo "no address on a global-scope interface"; exit 1; }
    node -e "require(\"http\").createServer((q,r)=>r.end(\"peer\")).listen(18080,\"$me\")" &
    pid=$!
    sleep 1
    code=$(timeout 10 curl -s -o /dev/null -w "%{http_code}" -x http://127.0.0.1:3128 "http://$me:18080/" || echo 000)
    kill $pid 2>/dev/null
    echo "  $me:18080 via the proxy -> $code"
    [ "$code" = 200 ] || { grep -n "^\^[0-9]" /etc/devcontainer/egress-filter/allow.regex; exit 1; }'

# The pattern is the subnet and nothing wider: a public address literal is still refused, and so is
# a private one on a subnet this container is not attached to.
check "the address patterns do not reach past the local subnet" bash -c '
    for ip in 1.1.1.1 192.0.2.7 10.99.99.99; do
        code=$(timeout 10 curl -s -o /dev/null -w "%{http_code}" -x http://127.0.0.1:3128 "http://$ip/" || echo 000)
        echo "  $ip via the proxy -> $code"
        [ "$code" = 403 ] || { echo "$ip was not refused"; exit 1; }
    done'

check "a missing global mount is named, not silently skipped" bash -c '
    egress-status | tee /dev/stderr | grep -q "global:   NOT MOUNTED"'

# Deliberately not asserting anything about which hosts the *global* list happens to contain --
# that file belongs to whoever is running the tests. Everything below is self-contained: prove the
# host is blocked, allow it, prove it is reachable, and that nothing else became reachable with it.
check "a host on no list is blocked to begin with" bash -c '
    code=$(fetch example.com); echo "  example.com=$code"
    [ "$code" != 200 ] || { echo "reachable before being allowed; the filter is not filtering"; exit 1; }'

# The property that makes the lists maintainable: an edit takes effect on save, with no restart and
# no root, because policy lives in the proxy and the watcher reloads it on the file being written.
# The security property, and the reason there is no egress-allow command. The project list lives in
# the repo and the container user can write it -- so if it were re-read on change, the agent could
# widen its own allowlist by appending a line and waiting. It must not take effect on its own.
check "editing the project list does NOT take effect while running" bash -c '
    d=$(ls -d /workspaces/*/ | head -1); mkdir -p "$d.devcontainer"
    echo "example.com" >> "$d.devcontainer/egress-allow.txt"
    echo "  wrote example.com to $d.devcontainer/egress-allow.txt"
    sleep 6
    code=$(fetch example.com); echo "  example.com=$code"
    [ "$code" != 200 ] || { echo "the agent widened its own allowlist -- this is the hole"; exit 1; }'

# The global list, and the read-only mount that makes watching it safe, live in the `mounted-global`
# scenario -- see mounted-global.sh, which declares the mount the way a user does.

# ...and it IS honoured on the next start. That half needs root to rebuild, so it lives in the
# privileged scenario, together with everything that depends on the host being allowed afterwards.

# The point of the firewall rather than just the env var: ignoring the proxy does not help, even for
# a host that IS allowed. The baseline supplies one, so this needs nothing allowed first.
check "ignoring HTTP_PROXY does not get you out" bash -c '
    code=$(direct marketplace.visualstudio.com); echo "  direct to the allowed host=$code"
    [ "$code" != 200 ] || { echo "egress bypassed the proxy entirely"; exit 1; }'

check "DNS still resolves, as configured" bash -c '
    getent hosts example.com >/dev/null || { echo "resolution broken"; exit 1; }'

# Port 53 is the one hole a default-deny egress filter has to leave open, and open to *any*
# destination it is not a hole but a transport: iodine and dnscat need nothing more than a route to
# a nameserver the other end controls. So the accepts name a destination. Reading the chain needs
# root, so that check is in the privileged scenario. This is the same property from the outside,
# which is the half a non-root process can prove: skips a resolver that happens to be ours, and
# passes vacuously with no internet, which is the right way round for a negative test.
check "a nameserver that is not one of ours cannot be reached on 53" bash -c '
    for ns in 8.8.8.8 1.1.1.1; do
        grep -q "nameserver $ns" /etc/resolv.conf && continue
        if timeout 5 bash -c "exec 3<>/dev/tcp/$ns/53" 2>/dev/null; then
            echo "  opened tcp/53 to $ns -- DNS is a way out of here"; exit 1
        fi
        echo "  $ns refused on 53, as it must be"
    done'

check "egress-status says what port 53 may reach" bash -c '
    egress-status | tee /dev/stderr | grep -q "port 53 to "'

# The project list is named as a source whether or not it exists, so it can be found before it is
# written. It still reads "none yet" here: the file was created above, and the sources are re-read
# on a rebuild only. The privileged scenario checks the other side of that.
check "the project list is named as a source, and a mid-run edit does not change what status says" bash -c '
    egress-status | tee /dev/stderr | grep -q "project:  .devcontainer/egress-allow.txt (in this repo -- none yet)"'

# ---------------------------------------------------------------------------------------------
# The agent-facing half. A blocked request is a bare 403 that says nothing about a filter, and npm
# blames your dependency versions -- so an agent will reasonably retry, switch registries, or start
# disabling certificate checks. None of that can work. These check the explanation is actually
# reachable, from each of the places an agent might look.
# ---------------------------------------------------------------------------------------------

check "a blocked plain-HTTP request explains itself" bash -c '
    body=$(timeout 10 curl -s -x http://127.0.0.1:3128 http://blocked.example.net 2>&1)
    echo "$body" | grep -q "Blocked by egress-filter" || { echo "$body" | head -5; exit 1; }
    # The proxy substitutes the request, so the page names the host that was refused.
    echo "$body" | grep -q "blocked.example.net" || { echo "the page does not name the host"; exit 1; }
    echo "$body" | grep -q "cannot fix this yourself"'

check "the notes are installed and say what will not work" bash -c '
    f=/usr/local/share/devcontainer/egress-filter/BLOCKED.md
    test -r "$f"
    grep -q "no command in this container that adds a host" "$f"
    grep -q "strict-ssl" "$f"
    grep -q "read once at container start" "$f"'

# Written at container start, not build time: persist-homedir puts /home on a volume that would
# otherwise mask anything the image left in $HOME.
check "the agent skill landed in the remote user home, owned by the remote user" bash -c '
    f="$HOME/.claude/skills/egress-filter/SKILL.md"
    test -r "$f" || { echo "no skill at $f"; exit 1; }
    [ "$(stat -c %U "$f")" = "$(whoami)" ] || { echo "owned by $(stat -c %U "$f")"; exit 1; }
    head -1 "$f" | grep -q -- "---" || { echo "no frontmatter"; exit 1; }
    grep -q "^name: egress-filter" "$f"
    grep -q "^description: " "$f"
    # Skills are model-invoked: the description is the only thing Claude sees until it fires, so it
    # has to name the symptoms an agent will actually be looking at, not the cause it cannot see.
    d=$(grep "^description: " "$f")
    for sym in 403 "CONNECT tunnel failed" npm git TLS; do
        echo "$d" | grep -q "$sym" || { echo "description does not mention: $sym"; exit 1; }
    done
    echo "$d" | grep -qi "before retrying\|BEFORE retrying" || { echo "not directive enough"; exit 1; }'

check "the skill tells the agent to ask rather than work around it" bash -c '
    f="$HOME/.claude/skills/egress-filter/SKILL.md"
    grep -q "Ask the person you are working with" "$f"
    grep -q "applies immediately\|within ~2s" "$f"
    grep -q "needs a container restart\|after a container restart" "$f"'

reportResults
