#!/usr/bin/env bash
# Defaults, which means the filter is on -- installing the feature is what turns it on, so the
# autogenerated test exercises the real configuration rather than a special one.
#
# The checks that matter are the two ends of it: an allowed host is reachable, and a host that is
# on no list is not reachable *by any route*, including one that ignores HTTP_PROXY.
set -e
source dev-container-features-test-lib

fetch()  { timeout 15 curl -s -o /dev/null -w "%{http_code}" -x "http://127.0.0.1:3128" "https://$1" 2>/dev/null || echo 000; }
direct() { timeout 10 curl -s -o /dev/null -w "%{http_code}" --noproxy "*" "https://$1" 2>/dev/null || echo 000; }
export -f fetch direct

check "the tools and scripts landed" bash -c '
    command -v tinyproxy >/dev/null || { echo "no tinyproxy"; exit 1; }
    command -v iptables  >/dev/null || { echo "no iptables"; exit 1; }
    command -v egress-status >/dev/null
    # No command for widening the list from inside -- see the README.
    ! command -v egress-allow >/dev/null || { echo "egress-allow should not exist"; exit 1; }
    id egressfilter >/dev/null || { echo "no proxy uid"; exit 1; }
    test -r /usr/local/share/nshafer-egress-filter/config'

check "the filter came up at container start" bash -c '
    egress-status | tee /dev/stderr
    egress-status | grep -q "listening on 127.0.0.1:3128"
    egress-status | grep -q "default deny"'

check "the baseline is merged, so VS Code can still reach the marketplace" bash -c '
    egress-status | grep -q "baseline:"
    grep -q "visualstudio" /etc/nshafer-egress-filter/allow.regex'

# The global list is a file on the host, mounted read-only.
# allow.regex is what the proxy reads and is unreadable at a glance: anchored, escaped, sorted, with
# no trace of where any line came from. The concatenated file answers "why is this host allowed" and
# "did my edit land", which is the question anyone actually has.
check "the concatenated allowlist is written, with a header per source" bash -c '
    f=/etc/nshafer-egress-filter/allowlist.txt
    test -r "$f" || { echo "not written"; exit 1; }
    grep -q "^# baseline: " "$f" || { echo "no baseline header"; sed -n 1,20p "$f"; exit 1; }
    grep -q "^# global: "   "$f" || { echo "no global header"; exit 1; }
    # The header names the host-side path, not the mount, for the same reason the status does.
    grep -q "^# global: ~/.config/egress-filter/allowlist.txt" "$f"         || { echo "global header does not name the host path"; grep "^# global" "$f"; exit 1; }
    grep -q "rewritten on every reload" "$f" || { echo "no do-not-edit warning"; exit 1; }'

check "it carries the source comments through, not just the hosts" bash -c '
    f=/etc/nshafer-egress-filter/allowlist.txt
    # The baseline explains itself; that explanation is the useful part when reading this file.
    grep -q "cannot reach the marketplace" "$f" || { echo "source comments were stripped"; exit 1; }
    grep -q "marketplace.visualstudio.com" "$f" || { echo "baseline hosts missing"; exit 1; }'

check "status points at it, so it can be found" bash -c '
    egress-status | tee /dev/stderr         | grep -qE "allowlist +[0-9]+ patterns \(/etc/nshafer-egress-filter/allowlist.txt\)"'

check "it is readable without root" bash -c '
    head -1 /etc/nshafer-egress-filter/allowlist.txt >/dev/null || { echo "cannot read as $(whoami)"; exit 1; }'

check "the global list on the host is merged" bash -c '
    test -r /mnt/egress-filter/allowlist.txt || { echo "global list not mounted"; exit 1; }
    egress-status | grep -q "global:"'

# Deliberately not asserting anything about which hosts the *global* list happens to contain --
# that file belongs to whoever is running the tests. Everything below is self-contained: prove the
# host is blocked, allow it, prove it is reachable, and that nothing else became reachable with it.
check "a host on no list is blocked to begin with" bash -c '
    code=$(fetch example.com); echo "  example.com=$code"
    [ "$code" != 200 ] || { echo "reachable before being allowed; the filter is not filtering"; exit 1; }'

# The property that makes the lists maintainable: an edit takes effect on save, with no restart and
# no root, because policy lives in the proxy and the watcher reloads it on the file being written.
# The security property, and the reason there is no egress-allow command. The project list lives in
# the repo and the container user can write it -- so if it were re-read on change, the agent could
# widen its own allowlist by appending a line and waiting. It must not take effect on its own.
check "editing the project list does NOT take effect while running" bash -c '
    d=$(ls -d /workspaces/*/ | head -1); mkdir -p "$d.devcontainer"
    echo "example.com" >> "$d.devcontainer/egress-allow.txt"
    echo "  wrote example.com to $d.devcontainer/egress-allow.txt"
    sleep 6
    code=$(fetch example.com); echo "  example.com=$code"
    [ "$code" != 200 ] || { echo "the agent widened its own allowlist -- this is the hole"; exit 1; }'

check "the global list is read-only from inside, which is why it can be watched" bash -c '
    echo evil.example.net >> /mnt/egress-filter/allowlist.txt 2>&1 | sed "s/^/  /"
    ! grep -q evil /mnt/egress-filter/allowlist.txt 2>/dev/null \
        || { echo "the container could write the global list"; exit 1; }
    echo "  refused, as it must be"'

# ...and it IS honoured on the next start, which is what makes the project list useful at all.
check "the project list is picked up by a privileged rebuild, as a restart would" bash -c '
    sudo -n /usr/local/share/nshafer-egress-filter/egress.sh reload >/dev/null 2>&1
    for _ in $(seq 1 10); do
        code=$(fetch example.com); [ "$code" = 200 ] && break
        sleep 1
    done
    echo "  example.com=$code"
    [ "$code" = 200 ] || { echo "a restart would not have picked it up either"; exit 1; }'

check "allowing one host did not open the rest" bash -c '
    code=$(fetch neverallowed.example.net); echo "  neverallowed.example.net=$code"
    [ "$code" != 200 ]'

# The point of the firewall rather than just the env var: ignoring the proxy does not help, even for
# a host that IS allowed.
check "ignoring HTTP_PROXY does not get you out" bash -c '
    code=$(direct example.com); echo "  direct to the allowed host=$code"
    [ "$code" != 200 ] || { echo "egress bypassed the proxy entirely"; exit 1; }'

check "DNS still resolves, as configured" bash -c '
    getent hosts example.com >/dev/null || { echo "resolution broken"; exit 1; }'

# Port 53 is the one hole a default-deny egress filter has to leave open, and open to *any*
# destination it is not a hole but a transport: iodine and dnscat need nothing more than a route to
# a nameserver the other end controls. So the accepts name a destination, and the destinations are
# the resolvers this container was actually given.
check "port 53 is pinned to the resolvers this container was given" bash -c '
    rules=$(sudo -n iptables -S NSHAFER_EGRESS)
    dns=$(echo "$rules" | grep -- "--dport 53" || true)
    echo "$dns" | sed "s/^/  /"
    [ -n "$dns" ] || { echo "no DNS rules at all"; exit 1; }
    open=$(echo "$dns" | grep -- "-j ACCEPT" | grep -cv -- " -d " || true)
    [ "$open" = 0 ] || { echo "$open DNS accepts with no destination -- 53 is open to the world"; exit 1; }
    for ns in $(sed -n "s/^nameserver  *//p" /etc/resolv.conf); do
        case "$ns" in *:*) continue ;; esac
        echo "$dns" | grep -q -- " -d $ns" || { echo "resolver $ns was not pinned"; exit 1; }
    done
    echo "  every accept on 53 carries a destination"'

# The same property from the other side of the firewall. Skips a resolver that happens to be ours,
# and passes vacuously with no internet, which is the right way round for a negative test.
check "a nameserver that is not one of ours cannot be reached on 53" bash -c '
    for ns in 8.8.8.8 1.1.1.1; do
        grep -q "nameserver $ns" /etc/resolv.conf && continue
        if timeout 5 bash -c "exec 3<>/dev/tcp/$ns/53" 2>/dev/null; then
            echo "  opened tcp/53 to $ns -- DNS is a way out of here"; exit 1
        fi
        echo "  $ns refused on 53, as it must be"
    done'

check "egress-status says what port 53 may reach" bash -c '
    egress-status | tee /dev/stderr | grep -q "port 53 to "'

check "the project list is reported as a source once it exists" bash -c '
    egress-status | tee /dev/stderr | grep -q "project:  /workspaces"'

# ---------------------------------------------------------------------------------------------
# The agent-facing half. A blocked request is a bare 403 that says nothing about a filter, and npm
# blames your dependency versions -- so an agent will reasonably retry, switch registries, or start
# disabling certificate checks. None of that can work. These check the explanation is actually
# reachable, from each of the places an agent might look.
# ---------------------------------------------------------------------------------------------

check "a blocked plain-HTTP request explains itself" bash -c '
    body=$(timeout 10 curl -s -x http://127.0.0.1:3128 http://blocked.example.net 2>&1)
    echo "$body" | grep -q "Blocked by egress-filter" || { echo "$body" | head -5; exit 1; }
    # The proxy substitutes the request, so the page names the host that was refused.
    echo "$body" | grep -q "blocked.example.net" || { echo "the page does not name the host"; exit 1; }
    echo "$body" | grep -q "cannot fix this yourself"'

check "the notes are installed and say what will not work" bash -c '
    f=/usr/local/share/nshafer-egress-filter/BLOCKED.md
    test -r "$f"
    grep -q "no command in this container that adds a host" "$f"
    grep -q "strict-ssl" "$f"
    grep -q "read once at container start" "$f"'

# Written at container start, not build time: persist-homedir puts /home on a volume that would
# otherwise mask anything the image left in $HOME.
check "the agent skill landed in the remote user home, owned by the remote user" bash -c '
    f="$HOME/.claude/skills/egress-filter/SKILL.md"
    test -r "$f" || { echo "no skill at $f"; exit 1; }
    [ "$(stat -c %U "$f")" = "$(whoami)" ] || { echo "owned by $(stat -c %U "$f")"; exit 1; }
    head -1 "$f" | grep -q -- "---" || { echo "no frontmatter"; exit 1; }
    grep -q "^name: egress-filter" "$f"
    grep -q "^description: " "$f"
    # Skills are model-invoked: the description is the only thing Claude sees until it fires, so it
    # has to name the symptoms an agent will actually be looking at, not the cause it cannot see.
    d=$(grep "^description: " "$f")
    for sym in 403 "CONNECT tunnel failed" npm git TLS; do
        echo "$d" | grep -q "$sym" || { echo "description does not mention: $sym"; exit 1; }
    done
    echo "$d" | grep -qi "before retrying\|BEFORE retrying" || { echo "not directive enough"; exit 1; }'

check "the skill tells the agent to ask rather than work around it" bash -c '
    f="$HOME/.claude/skills/egress-filter/SKILL.md"
    grep -q "Ask the person you are working with" "$f"
    grep -q "applies immediately\|within ~2s" "$f"
    grep -q "needs a container restart\|after a container restart" "$f"'

reportResults
