#!/usr/bin/env bash
# Build-time half: stash the scripts, bake the options into a config the runtime can read, wire the
# environment scrub into the shells, and take the two fixed paths before anyone else can.
#
# None of the actual blocking happens here, and that is deliberate rather than a limitation. The
# sockets this feature exists to cut are created when VS Code attaches, long after the image is
# built -- and an earlier version that claimed their directories in advance, so they could never be
# created, made the container impossible to attach to: VS Code's helper failed to set up forwarding
# and sat on "Configuring Dev Container" forever. See the note above block_fixed in sandbox.sh.
# Everything is therefore left to the entrypoint and the sweeper, which act after the fact.
set -euo pipefail

BLOCK_SSH="${BLOCKSSHAGENT:-true}"
BLOCK_GPG="${BLOCKGPGAGENT:-true}"
BLOCK_X11="${BLOCKX11:-true}"
BLOCK_IPC="${BLOCKVSCODEIPC:-true}"
SCRUB_ENV="${SCRUBENV:-true}"
SWEEP_INTERVAL="${SWEEPINTERVAL:-1}"

SHARE_DIR=/usr/local/share/nshafer-sandbox

case "$SWEEP_INTERVAL" in
    '' | *[!0-9]*)
        echo "!!! sandbox: sweepInterval must be a whole number of seconds. Received: $SWEEP_INTERVAL" >&2
        exit 1
        ;;
esac

USERNAME="${_REMOTE_USER:-root}"
USER_HOME="${_REMOTE_USER_HOME:-}"
if [ -z "$USER_HOME" ] || [ ! -d "$USER_HOME" ]; then
    USER_HOME="$(getent passwd "$USERNAME" 2>/dev/null | cut -d: -f6 || true)"
fi
: "${USER_HOME:=/home/$USERNAME}"
USER_UID="$(id -u "$USERNAME" 2>/dev/null || echo 0)"

echo "==> sandbox: user=$USERNAME home=$USER_HOME uid=$USER_UID"
echo "==> sandbox: ssh=$BLOCK_SSH gpg=$BLOCK_GPG x11=$BLOCK_X11 ipc=$BLOCK_IPC scrubEnv=$SCRUB_ENV"

if [ "$USERNAME" = "root" ]; then
    echo "!!! sandbox: the remote user is root, so nothing here is a real boundary -- root can" >&2
    echo "!!!   chmod any tombstone back. Set remoteUser to a non-root user." >&2
fi

install -d "$SHARE_DIR"
install -m 0755 sandbox.sh "$SHARE_DIR/sandbox.sh"
install -m 0755 entrypoint.sh "$SHARE_DIR/entrypoint.sh"
install -m 0755 post-start.sh "$SHARE_DIR/post-start.sh"
install -m 0755 post-attach.sh "$SHARE_DIR/post-attach.sh"
install -m 0644 scrub-env.sh "$SHARE_DIR/scrub-env.sh"

# The runtime scripts are lifecycle commands and entrypoints: static strings, handed no options.
# Only this script ever sees an option value, so the choices are written down here for it to read.
cat > "$SHARE_DIR/config" <<EOF
# Generated by the sandbox devcontainer feature at build time. Read by sandbox.sh.
BLOCK_SSH=$BLOCK_SSH
BLOCK_GPG=$BLOCK_GPG
BLOCK_X11=$BLOCK_X11
BLOCK_IPC=$BLOCK_IPC
SWEEP_INTERVAL=$SWEEP_INTERVAL
USERNAME=$USERNAME
USER_HOME=$USER_HOME
USER_UID=$USER_UID
EOF
chmod 0644 "$SHARE_DIR/config"

# A read-only view of the truth, for a human or a test: `sandbox-report` exits non-zero if any
# channel is still reachable. Unprivileged -- it only stats paths.
cat > /usr/local/bin/sandbox-report <<EOF
#!/bin/sh
exec $SHARE_DIR/sandbox.sh report
EOF
chmod 0755 /usr/local/bin/sandbox-report

# The environment scrub, hooked into every kind of shell. All four hooks live in /etc, never in
# \$HOME: a persisted home volume masks whatever the image wrote to ~/.bashrc, so a scrub installed
# there works exactly once and then quietly stops on the next rebuild. ($BASH_ENV is the fourth,
# and it is set as the feature's containerEnv rather than here.)
if [ "$SCRUB_ENV" = true ]; then
    install -d /etc/profile.d
    cat > /etc/profile.d/00-nshafer-sandbox.sh <<EOF
# Installed by the sandbox devcontainer feature.
. $SHARE_DIR/scrub-env.sh
EOF
    chmod 0644 /etc/profile.d/00-nshafer-sandbox.sh

    for rc in /etc/bash.bashrc /etc/zsh/zshenv; do
        install -d "$(dirname "$rc")"
        touch "$rc"
        if ! grep -qF "$SHARE_DIR/scrub-env.sh" "$rc" 2>/dev/null; then
            {
                echo ""
                echo "# Installed by the sandbox devcontainer feature."
                echo ". $SHARE_DIR/scrub-env.sh"
            } >> "$rc"
        fi
    done
    echo "==> sandbox: env scrub wired into profile.d, bash.bashrc, zshenv and BASH_ENV"
fi

echo "==> sandbox: build stage done"
