#!/usr/bin/env bash
# Downloads the Tidewave CLI at build time and generates the postStart script that runs it.
#
# The binary goes to /usr/local/bin, not the home directory: the CLI has no self-updater to keep a
# canonical layout for, and /usr/local is the one place a persisted home volume cannot mask (see
# the persist-homedir feature, which puts /home on a volume that shadows whatever the image left
# in $HOME).
#
# The libc build is chosen to match the image, and the reason is not the CLI itself -- that asset is
# static and runs anywhere. It is the Bun runtime the CLI downloads at first use, into
# ~/.cache/tidewave/downloads. The CLI picks which Bun to fetch from its own build triple, which it
# reports verbatim (POST /about) with no idea what the host libc actually is, so a musl CLI on
# Debian fetches bun-linux-x64-musl and the image has no loader for it:
#
#   sh: 1: /home/node/.cache/tidewave/downloads/bun-linux-x64-musl-1-3-10: not found
#
# glibc unless the image is genuinely musl, therefore. Detected rather than optioned, because the
# right answer is a property of the base image and nobody should have to know it.
#
# Starting the CLI is the postStart script's job rather than this one's: the process has to run as
# the remote user, in the workspace folder, and neither of those exists yet at build time.
set -euo pipefail

VERSION="${VERSION:-latest}"
PORT="${PORT:-9000}"
ALLOW_REMOTE_ACCESS="${ALLOWREMOTEACCESS:-true}"
DEBUG="${DEBUG:-false}"
AUTOSTART="${AUTOSTART:-true}"

SHARE_DIR=/usr/local/share/devcontainer/tidewave
BINARY=/usr/local/bin/tidewave
RELEASES=https://github.com/tidewave-ai/tidewave_app/releases

case "$PORT" in
    '' | *[!0-9]*)
        echo "!!! tidewave: port must be a number. Received: $PORT" >&2
        exit 1
        ;;
esac

# uname -m reports what the kernel calls the architecture; the release assets use the Rust triple
# spelling. Everything else is unbuilt upstream, so say so here rather than 404ing on the download.
case "$(uname -m)" in
    x86_64 | amd64) ARCH=x86_64 ;;
    aarch64 | arm64) ARCH=aarch64 ;;
    *)
        echo "!!! tidewave: no CLI release for $(uname -m); only x86_64 and aarch64 are built" >&2
        exit 1
        ;;
esac

# musl's ldd names itself in its version banner and exits non-zero, hence the redirect; the loader
# file is the fallback for an image with no ldd at all. Anything unrecognised gets gnu, which is the
# right guess for every non-Alpine base image in circulation.
if ldd --version 2>&1 | grep -qi musl; then
    LIBC=musl
elif [ -e "/lib/ld-musl-$ARCH.so.1" ]; then
    LIBC=musl
else
    LIBC=gnu
fi

if [ "$VERSION" = "latest" ]; then
    URL="$RELEASES/latest/download/tidewave-cli-$ARCH-unknown-linux-$LIBC"
else
    URL="$RELEASES/download/v${VERSION#v}/tidewave-cli-$ARCH-unknown-linux-$LIBC"
fi

echo "==> tidewave: arch=$ARCH libc=$LIBC version=$VERSION port=$PORT debug=$DEBUG autostart=$AUTOSTART"

if ! command -v curl >/dev/null 2>&1; then
    echo "==> tidewave: installing curl"
    if command -v apt-get >/dev/null 2>&1; then
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -y
        apt-get install -y --no-install-recommends curl ca-certificates
        rm -rf /var/lib/apt/lists/*
    elif command -v apk >/dev/null 2>&1; then
        apk add --no-cache curl ca-certificates
    else
        echo "!!! tidewave: no curl and no known package manager" >&2
        exit 1
    fi
fi

echo "==> tidewave: downloading $URL"
# Written beside the target and renamed in, so a half-finished download never lands on the path a
# later layer or a running container would execute. -f turns a 404 -- a version that does not exist
# -- into a build failure here, instead of an HTML error page installed as the binary.
curl -fsSL -o "$BINARY.new" "$URL"
chmod 0755 "$BINARY.new"
mv -f "$BINARY.new" "$BINARY"

# The startup flags are fixed at build time because options are only visible to this script: a
# feature's lifecycle command is a static string, and it is handed no options of its own. Same
# reason autostart is written to the config below rather than expressed as a lifecycle hook that is
# simply absent -- postStartCommand is metadata, and metadata cannot be conditional.
ARGS="--port $PORT"
if [ "$ALLOW_REMOTE_ACCESS" = "true" ]; then
    ARGS="$ARGS --allow-remote-access"
fi
if [ "$DEBUG" = "true" ]; then
    ARGS="$ARGS --debug"
fi

install -d "$SHARE_DIR"
install -m 0755 post-start.sh "$SHARE_DIR/post-start.sh"
cat > "$SHARE_DIR/config" <<EOF
# Generated by the tidewave devcontainer feature at build time. Read by post-start.sh.
AUTOSTART=$AUTOSTART
PORT=$PORT
ARGS="$ARGS"
EOF
chmod 0644 "$SHARE_DIR/config"

echo "==> tidewave: installed $("$BINARY" --version)"
