#!/usr/bin/env bash
# The autogenerated test declares no mount, which is now the interesting case: the feature does not
# declare one either, so this is what a user gets before they add it. The first check is the warning
# that tells them. Everything after it is driven with a synthetic source directory, so it exercises
# the copy and the cleanup pass without a real /mnt/git-config.
#
# The checks that read the host's own git directory live in the `mounted` scenario -- see
# mounted.sh, which declares the mount the way a user does.
set -e
source dev-container-features-test-lib

check "git is installed" git --version

# postCreateCommand does not run in this harness, so drive the copy directly.
check "warns when the mount is missing, and does not stop the container" bash -c '
    out=$(/usr/local/share/devcontainer/git-config/post-create.sh 2>&1) \
        || { echo "  exited non-zero, which would break the container"; exit 1; }
    echo "$out" | sed "s/^/  /"
    echo "$out" | grep -q "/mnt/git-config is not there" || { echo "no warning"; exit 1; }
    echo "$out" | grep -q "type=bind,src=" || { echo "the devcontainer.json form is not named"; exit 1; }
    echo "$out" | grep -q ":/mnt/git-config:ro" || { echo "the compose form is not named"; exit 1; }
    [ ! -e "$HOME/.config/git/config" ] || { echo "wrote a config with no source"; exit 1; }'

# The cleanup pass, driven with a synthetic source so it does not depend on the host's config.
check "unsets keys naming a program this container lacks, keeps the rest" bash -c '
    src=$(mktemp -d); home=$(mktemp -d)
    printf "%s\n" \
        "[core]" \
        "	editor = definitely-not-installed-xyz --wait" \
        "	sshCommand = cat" \
        "[gpg]" \
        "	program = also-not-installed-xyz" \
        "[http]" \
        "	sslBackend = schannel" \
        "[filter \"lfs\"]" \
        "	clean = git-lfs clean -- %f" \
        "	required = true" \
        "[user]" \
        "	name = Synthetic" > "$src/config"
    out=$(GIT_CONFIG_SOURCE_DIR="$src" HOME="$home" /usr/local/share/devcontainer/git-config/post-create.sh 2>&1)
    g() { HOME="$home" git config --global --get "$1" 2>/dev/null || true; }
    [ -z "$(g core.editor)" ]        || { echo "core.editor survived"; exit 1; }
    [ -z "$(g gpg.program)" ]        || { echo "gpg.program survived"; exit 1; }
    [ -z "$(g http.sslBackend)" ]    || { echo "http.sslBackend survived"; exit 1; }
    [ "$(g core.sshCommand)" = cat ] || { echo "core.sshCommand was dropped"; exit 1; }
    [ "$(g user.name)" = Synthetic ] || { echo "unrelated config lost"; exit 1; }
    # The lfs filter is deliberately left in place: its failure is the signal to install git-lfs.
    [ "$(g filter.lfs.required)" = true ] || { echo "lfs filter was stripped"; exit 1; }
    echo "$out" | grep -q "definitely-not-installed-xyz is not installed" || { echo "no reason given"; exit 1; }
    exit 0'

# Also driven with a synthetic source: a host config carries helpers this container cannot run --
# a stale /tmp/vscode-remote-containers-<uuid>.js path the VS Code extension left in the host's
# global config, and a helper naming a program of the host such as gh.
check "drops every credential section, keeps the rest" bash -c '
    src=$(mktemp -d); home=$(mktemp -d)
    printf "%s\n" \
        "[credential]" \
        "	helper = !/tmp/vscode-remote-containers-dead.js git-credential-helper" \
        "	useHttpPath = true" \
        "[credential \"https://github.com\"]" \
        "	helper = !/usr/bin/gh auth git-credential" \
        "[user]" \
        "	name = Synthetic" > "$src/config"
    out=$(GIT_CONFIG_SOURCE_DIR="$src" HOME="$home" /usr/local/share/devcontainer/git-config/post-create.sh 2>&1)
    g() { HOME="$home" git config --global --get "$1" 2>/dev/null || true; }
    [ -z "$(g credential.helper)" ]      || { echo "credential.helper survived"; exit 1; }
    [ -z "$(g credential.useHttpPath)" ] || { echo "credential.useHttpPath survived"; exit 1; }
    [ -z "$(g "credential.https://github.com.helper")" ] || { echo "subsection survived"; exit 1; }
    grep -qi credential "$home/.config/git/config" && { echo "credential text left in the file"; exit 1; }
    [ "$(g user.name)" = Synthetic ] || { echo "unrelated config lost"; exit 1; }
    echo "$out" | grep -q "dropped \[credential\]" || { echo "no reason given"; exit 1; }
    exit 0'

check "is idempotent" bash -c '
    src=$(mktemp -d); home=$(mktemp -d)
    printf "%s\n" "[user]" "	name = Synthetic" > "$src/config"
    run() { GIT_CONFIG_SOURCE_DIR="$src" HOME="$home" /usr/local/share/devcontainer/git-config/post-create.sh >/dev/null 2>&1; }
    run; a=$(md5sum < "$home/.config/git/config")
    run; [ "$a" = "$(md5sum < "$home/.config/git/config")" ]'

check "will not clobber a file it did not write" bash -c '
    src=$(mktemp -d); home=$(mktemp -d)
    printf "%s\n" "keep me" > "$src/ignore"
    mkdir -p "$home/.config/git"; echo "not ours" > "$home/.config/git/ignore"
    GIT_CONFIG_SOURCE_DIR="$src" HOME="$home" /usr/local/share/devcontainer/git-config/post-create.sh 2>&1 \
        | grep -q "leaving it alone"
    [ "$(cat "$home/.config/git/ignore")" = "not ours" ]'

reportResults
